[package]
name = "webbed_hook_core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"
iso8601 = { version = "=0.6.3", features = ["serde", "chrono"] }
chrono = { version = "=0.4.44", features = ["serde"] }
