[package]
name = "webbed_hook_receiver"
version = "0.1.0"
edition = "2024"

[dependencies]
webbed_hook_core = { path = "../core" }
actix-web = "=4.12.1"
log = "=0.4.29"
env_logger = "=0.11.8"
regex = "=1.12.2"
unidiff = "=0.4.0"
